// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { normalizePostgresUrlForPrisma } from "./lib/normalizePostgresUrl";

/** Pooled URL (e.g. Supabase transaction mode :6543) — used by the app via lib/prisma.ts */
const poolUrl = process.env["POSTGRES_PRISMA_URL"] ?? "";
/** Session or direct DB URL (e.g. Supabase :5432 on pooler) — required for stable `db push` / migrate */
const directUrl = process.env["POSTGRES_URL_NON_POOLING"] ?? "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI must not use transaction-pooled connections; they can hit
    // "prepared statement sN already exists" on PgBouncer.
    url: directUrl || normalizePostgresUrlForPrisma(poolUrl),
  },
});
